version: '3.8'

services:
  app:
    build:
      context: ./.docker/nginx-unit
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/nginx-unit/php.ini:/usr/local/etc/php/php.ini'
    container_name: nginx-unit-test
    ports:
      - 80:80
